// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"
	"time"

	"github.com/alkk/tg-mcp/pkg/store"
)

// MessageStore is a mock implementation of server.messageStore.
//
//	func TestSomethingThatUsesmessageStore(t *testing.T) {
//
//		// make and configure a mocked server.messageStore
//		mockedmessageStore := &MessageStore{
//			CachedFunc: func(fileUniqueID string) (string, bool) {
//				panic("mock out the Cached method")
//			},
//			HistoryFunc: func(ctx context.Context, chatIDs []int64, from time.Time, to time.Time, before *store.HistoryCursor, limit int) ([]store.Message, error) {
//				panic("mock out the History method")
//			},
//			ListNewFunc: func(ctx context.Context, chatIDs []int64, limit int) ([]store.Message, error) {
//				panic("mock out the ListNew method")
//			},
//			MessageByIDFunc: func(ctx context.Context, chatID int64, messageID int64) (store.Message, error) {
//				panic("mock out the MessageByID method")
//			},
//			SaveFileFunc: func(fileUniqueID string, write func(w io.Writer) error) (string, error) {
//				panic("mock out the SaveFile method")
//			},
//			SearchFunc: func(ctx context.Context, query string, chatIDs []int64, from time.Time, to time.Time, limit int) ([]store.SearchHit, error) {
//				panic("mock out the Search method")
//			},
//			SetCursorFunc: func(ctx context.Context, chatID int64, messageID int64) (int64, error) {
//				panic("mock out the SetCursor method")
//			},
//			ThreadFunc: func(ctx context.Context, chatID int64, messageID int64) (store.Thread, error) {
//				panic("mock out the Thread method")
//			},
//			UnreadCountsFunc: func(ctx context.Context, chatIDs []int64) (map[int64]int, error) {
//				panic("mock out the UnreadCounts method")
//			},
//			UpsertMessageFunc: func(ctx context.Context, m store.Message) error {
//				panic("mock out the UpsertMessage method")
//			},
//		}
//
//		// use mockedmessageStore in code that requires server.messageStore
//		// and then make assertions.
//
//	}
type MessageStore struct {
	// CachedFunc mocks the Cached method.
	CachedFunc func(fileUniqueID string) (string, bool)

	// HistoryFunc mocks the History method.
	HistoryFunc func(ctx context.Context, chatIDs []int64, from time.Time, to time.Time, before *store.HistoryCursor, limit int) ([]store.Message, error)

	// ListNewFunc mocks the ListNew method.
	ListNewFunc func(ctx context.Context, chatIDs []int64, limit int) ([]store.Message, error)

	// MessageByIDFunc mocks the MessageByID method.
	MessageByIDFunc func(ctx context.Context, chatID int64, messageID int64) (store.Message, error)

	// SaveFileFunc mocks the SaveFile method.
	SaveFileFunc func(fileUniqueID string, write func(w io.Writer) error) (string, error)

	// SearchFunc mocks the Search method.
	SearchFunc func(ctx context.Context, query string, chatIDs []int64, from time.Time, to time.Time, limit int) ([]store.SearchHit, error)

	// SetCursorFunc mocks the SetCursor method.
	SetCursorFunc func(ctx context.Context, chatID int64, messageID int64) (int64, error)

	// ThreadFunc mocks the Thread method.
	ThreadFunc func(ctx context.Context, chatID int64, messageID int64) (store.Thread, error)

	// UnreadCountsFunc mocks the UnreadCounts method.
	UnreadCountsFunc func(ctx context.Context, chatIDs []int64) (map[int64]int, error)

	// UpsertMessageFunc mocks the UpsertMessage method.
	UpsertMessageFunc func(ctx context.Context, m store.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Cached holds details about calls to the Cached method.
		Cached []struct {
			// FileUniqueID is the fileUniqueID argument value.
			FileUniqueID string
		}
		// History holds details about calls to the History method.
		History []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatIDs is the chatIDs argument value.
			ChatIDs []int64
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Before is the before argument value.
			Before *store.HistoryCursor
			// Limit is the limit argument value.
			Limit int
		}
		// ListNew holds details about calls to the ListNew method.
		ListNew []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatIDs is the chatIDs argument value.
			ChatIDs []int64
			// Limit is the limit argument value.
			Limit int
		}
		// MessageByID holds details about calls to the MessageByID method.
		MessageByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// SaveFile holds details about calls to the SaveFile method.
		SaveFile []struct {
			// FileUniqueID is the fileUniqueID argument value.
			FileUniqueID string
			// Write is the write argument value.
			Write func(w io.Writer) error
		}
		// Search holds details about calls to the Search method.
		Search []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// ChatIDs is the chatIDs argument value.
			ChatIDs []int64
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// SetCursor holds details about calls to the SetCursor method.
		SetCursor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// Thread holds details about calls to the Thread method.
		Thread []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// UnreadCounts holds details about calls to the UnreadCounts method.
		UnreadCounts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatIDs is the chatIDs argument value.
			ChatIDs []int64
		}
		// UpsertMessage holds details about calls to the UpsertMessage method.
		UpsertMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M store.Message
		}
	}
	lockCached        sync.RWMutex
	lockHistory       sync.RWMutex
	lockListNew       sync.RWMutex
	lockMessageByID   sync.RWMutex
	lockSaveFile      sync.RWMutex
	lockSearch        sync.RWMutex
	lockSetCursor     sync.RWMutex
	lockThread        sync.RWMutex
	lockUnreadCounts  sync.RWMutex
	lockUpsertMessage sync.RWMutex
}

// Cached calls CachedFunc.
func (mock *MessageStore) Cached(fileUniqueID string) (string, bool) {
	if mock.CachedFunc == nil {
		panic("MessageStore.CachedFunc: method is nil but messageStore.Cached was just called")
	}
	callInfo := struct {
		FileUniqueID string
	}{
		FileUniqueID: fileUniqueID,
	}
	mock.lockCached.Lock()
	mock.calls.Cached = append(mock.calls.Cached, callInfo)
	mock.lockCached.Unlock()
	return mock.CachedFunc(fileUniqueID)
}

// CachedCalls gets all the calls that were made to Cached.
// Check the length with:
//
//	len(mockedmessageStore.CachedCalls())
func (mock *MessageStore) CachedCalls() []struct {
	FileUniqueID string
} {
	var calls []struct {
		FileUniqueID string
	}
	mock.lockCached.RLock()
	calls = mock.calls.Cached
	mock.lockCached.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *MessageStore) History(ctx context.Context, chatIDs []int64, from time.Time, to time.Time, before *store.HistoryCursor, limit int) ([]store.Message, error) {
	if mock.HistoryFunc == nil {
		panic("MessageStore.HistoryFunc: method is nil but messageStore.History was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChatIDs []int64
		From    time.Time
		To      time.Time
		Before  *store.HistoryCursor
		Limit   int
	}{
		Ctx:     ctx,
		ChatIDs: chatIDs,
		From:    from,
		To:      to,
		Before:  before,
		Limit:   limit,
	}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	return mock.HistoryFunc(ctx, chatIDs, from, to, before, limit)
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedmessageStore.HistoryCalls())
func (mock *MessageStore) HistoryCalls() []struct {
	Ctx     context.Context
	ChatIDs []int64
	From    time.Time
	To      time.Time
	Before  *store.HistoryCursor
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		ChatIDs []int64
		From    time.Time
		To      time.Time
		Before  *store.HistoryCursor
		Limit   int
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}

// ListNew calls ListNewFunc.
func (mock *MessageStore) ListNew(ctx context.Context, chatIDs []int64, limit int) ([]store.Message, error) {
	if mock.ListNewFunc == nil {
		panic("MessageStore.ListNewFunc: method is nil but messageStore.ListNew was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChatIDs []int64
		Limit   int
	}{
		Ctx:     ctx,
		ChatIDs: chatIDs,
		Limit:   limit,
	}
	mock.lockListNew.Lock()
	mock.calls.ListNew = append(mock.calls.ListNew, callInfo)
	mock.lockListNew.Unlock()
	return mock.ListNewFunc(ctx, chatIDs, limit)
}

// ListNewCalls gets all the calls that were made to ListNew.
// Check the length with:
//
//	len(mockedmessageStore.ListNewCalls())
func (mock *MessageStore) ListNewCalls() []struct {
	Ctx     context.Context
	ChatIDs []int64
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		ChatIDs []int64
		Limit   int
	}
	mock.lockListNew.RLock()
	calls = mock.calls.ListNew
	mock.lockListNew.RUnlock()
	return calls
}

// MessageByID calls MessageByIDFunc.
func (mock *MessageStore) MessageByID(ctx context.Context, chatID int64, messageID int64) (store.Message, error) {
	if mock.MessageByIDFunc == nil {
		panic("MessageStore.MessageByIDFunc: method is nil but messageStore.MessageByID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockMessageByID.Lock()
	mock.calls.MessageByID = append(mock.calls.MessageByID, callInfo)
	mock.lockMessageByID.Unlock()
	return mock.MessageByIDFunc(ctx, chatID, messageID)
}

// MessageByIDCalls gets all the calls that were made to MessageByID.
// Check the length with:
//
//	len(mockedmessageStore.MessageByIDCalls())
func (mock *MessageStore) MessageByIDCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}
	mock.lockMessageByID.RLock()
	calls = mock.calls.MessageByID
	mock.lockMessageByID.RUnlock()
	return calls
}

// SaveFile calls SaveFileFunc.
func (mock *MessageStore) SaveFile(fileUniqueID string, write func(w io.Writer) error) (string, error) {
	if mock.SaveFileFunc == nil {
		panic("MessageStore.SaveFileFunc: method is nil but messageStore.SaveFile was just called")
	}
	callInfo := struct {
		FileUniqueID string
		Write        func(w io.Writer) error
	}{
		FileUniqueID: fileUniqueID,
		Write:        write,
	}
	mock.lockSaveFile.Lock()
	mock.calls.SaveFile = append(mock.calls.SaveFile, callInfo)
	mock.lockSaveFile.Unlock()
	return mock.SaveFileFunc(fileUniqueID, write)
}

// SaveFileCalls gets all the calls that were made to SaveFile.
// Check the length with:
//
//	len(mockedmessageStore.SaveFileCalls())
func (mock *MessageStore) SaveFileCalls() []struct {
	FileUniqueID string
	Write        func(w io.Writer) error
} {
	var calls []struct {
		FileUniqueID string
		Write        func(w io.Writer) error
	}
	mock.lockSaveFile.RLock()
	calls = mock.calls.SaveFile
	mock.lockSaveFile.RUnlock()
	return calls
}

// Search calls SearchFunc.
func (mock *MessageStore) Search(ctx context.Context, query string, chatIDs []int64, from time.Time, to time.Time, limit int) ([]store.SearchHit, error) {
	if mock.SearchFunc == nil {
		panic("MessageStore.SearchFunc: method is nil but messageStore.Search was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Query   string
		ChatIDs []int64
		From    time.Time
		To      time.Time
		Limit   int
	}{
		Ctx:     ctx,
		Query:   query,
		ChatIDs: chatIDs,
		From:    from,
		To:      to,
		Limit:   limit,
	}
	mock.lockSearch.Lock()
	mock.calls.Search = append(mock.calls.Search, callInfo)
	mock.lockSearch.Unlock()
	return mock.SearchFunc(ctx, query, chatIDs, from, to, limit)
}

// SearchCalls gets all the calls that were made to Search.
// Check the length with:
//
//	len(mockedmessageStore.SearchCalls())
func (mock *MessageStore) SearchCalls() []struct {
	Ctx     context.Context
	Query   string
	ChatIDs []int64
	From    time.Time
	To      time.Time
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		Query   string
		ChatIDs []int64
		From    time.Time
		To      time.Time
		Limit   int
	}
	mock.lockSearch.RLock()
	calls = mock.calls.Search
	mock.lockSearch.RUnlock()
	return calls
}

// SetCursor calls SetCursorFunc.
func (mock *MessageStore) SetCursor(ctx context.Context, chatID int64, messageID int64) (int64, error) {
	if mock.SetCursorFunc == nil {
		panic("MessageStore.SetCursorFunc: method is nil but messageStore.SetCursor was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockSetCursor.Lock()
	mock.calls.SetCursor = append(mock.calls.SetCursor, callInfo)
	mock.lockSetCursor.Unlock()
	return mock.SetCursorFunc(ctx, chatID, messageID)
}

// SetCursorCalls gets all the calls that were made to SetCursor.
// Check the length with:
//
//	len(mockedmessageStore.SetCursorCalls())
func (mock *MessageStore) SetCursorCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}
	mock.lockSetCursor.RLock()
	calls = mock.calls.SetCursor
	mock.lockSetCursor.RUnlock()
	return calls
}

// Thread calls ThreadFunc.
func (mock *MessageStore) Thread(ctx context.Context, chatID int64, messageID int64) (store.Thread, error) {
	if mock.ThreadFunc == nil {
		panic("MessageStore.ThreadFunc: method is nil but messageStore.Thread was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockThread.Lock()
	mock.calls.Thread = append(mock.calls.Thread, callInfo)
	mock.lockThread.Unlock()
	return mock.ThreadFunc(ctx, chatID, messageID)
}

// ThreadCalls gets all the calls that were made to Thread.
// Check the length with:
//
//	len(mockedmessageStore.ThreadCalls())
func (mock *MessageStore) ThreadCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}
	mock.lockThread.RLock()
	calls = mock.calls.Thread
	mock.lockThread.RUnlock()
	return calls
}

// UnreadCounts calls UnreadCountsFunc.
func (mock *MessageStore) UnreadCounts(ctx context.Context, chatIDs []int64) (map[int64]int, error) {
	if mock.UnreadCountsFunc == nil {
		panic("MessageStore.UnreadCountsFunc: method is nil but messageStore.UnreadCounts was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChatIDs []int64
	}{
		Ctx:     ctx,
		ChatIDs: chatIDs,
	}
	mock.lockUnreadCounts.Lock()
	mock.calls.UnreadCounts = append(mock.calls.UnreadCounts, callInfo)
	mock.lockUnreadCounts.Unlock()
	return mock.UnreadCountsFunc(ctx, chatIDs)
}

// UnreadCountsCalls gets all the calls that were made to UnreadCounts.
// Check the length with:
//
//	len(mockedmessageStore.UnreadCountsCalls())
func (mock *MessageStore) UnreadCountsCalls() []struct {
	Ctx     context.Context
	ChatIDs []int64
} {
	var calls []struct {
		Ctx     context.Context
		ChatIDs []int64
	}
	mock.lockUnreadCounts.RLock()
	calls = mock.calls.UnreadCounts
	mock.lockUnreadCounts.RUnlock()
	return calls
}

// UpsertMessage calls UpsertMessageFunc.
func (mock *MessageStore) UpsertMessage(ctx context.Context, m store.Message) error {
	if mock.UpsertMessageFunc == nil {
		panic("MessageStore.UpsertMessageFunc: method is nil but messageStore.UpsertMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   store.Message
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockUpsertMessage.Lock()
	mock.calls.UpsertMessage = append(mock.calls.UpsertMessage, callInfo)
	mock.lockUpsertMessage.Unlock()
	return mock.UpsertMessageFunc(ctx, m)
}

// UpsertMessageCalls gets all the calls that were made to UpsertMessage.
// Check the length with:
//
//	len(mockedmessageStore.UpsertMessageCalls())
func (mock *MessageStore) UpsertMessageCalls() []struct {
	Ctx context.Context
	M   store.Message
} {
	var calls []struct {
		Ctx context.Context
		M   store.Message
	}
	mock.lockUpsertMessage.RLock()
	calls = mock.calls.UpsertMessage
	mock.lockUpsertMessage.RUnlock()
	return calls
}
