// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"

	"github.com/alkk/tg-mcp/pkg/telegram"
)

// TelegramAPI is a mock implementation of server.telegramAPI.
//
//	func TestSomethingThatUsestelegramAPI(t *testing.T) {
//
//		// make and configure a mocked server.telegramAPI
//		mockedtelegramAPI := &TelegramAPI{
//			DownloadFunc: func(ctx context.Context, filePath string, dst io.Writer) error {
//				panic("mock out the Download method")
//			},
//			GetFileFunc: func(ctx context.Context, fileID string) (telegram.File, error) {
//				panic("mock out the GetFile method")
//			},
//			SendMessageFunc: func(ctx context.Context, chatID int64, text string, parseMode string, replyTo int64, threadID int64) (telegram.Message, error) {
//				panic("mock out the SendMessage method")
//			},
//		}
//
//		// use mockedtelegramAPI in code that requires server.telegramAPI
//		// and then make assertions.
//
//	}
type TelegramAPI struct {
	// DownloadFunc mocks the Download method.
	DownloadFunc func(ctx context.Context, filePath string, dst io.Writer) error

	// GetFileFunc mocks the GetFile method.
	GetFileFunc func(ctx context.Context, fileID string) (telegram.File, error)

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, chatID int64, text string, parseMode string, replyTo int64, threadID int64) (telegram.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// Download holds details about calls to the Download method.
		Download []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Dst is the dst argument value.
			Dst io.Writer
		}
		// GetFile holds details about calls to the GetFile method.
		GetFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FileID is the fileID argument value.
			FileID string
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Text is the text argument value.
			Text string
			// ParseMode is the parseMode argument value.
			ParseMode string
			// ReplyTo is the replyTo argument value.
			ReplyTo int64
			// ThreadID is the threadID argument value.
			ThreadID int64
		}
	}
	lockDownload    sync.RWMutex
	lockGetFile     sync.RWMutex
	lockSendMessage sync.RWMutex
}

// Download calls DownloadFunc.
func (mock *TelegramAPI) Download(ctx context.Context, filePath string, dst io.Writer) error {
	if mock.DownloadFunc == nil {
		panic("TelegramAPI.DownloadFunc: method is nil but telegramAPI.Download was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Dst      io.Writer
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Dst:      dst,
	}
	mock.lockDownload.Lock()
	mock.calls.Download = append(mock.calls.Download, callInfo)
	mock.lockDownload.Unlock()
	return mock.DownloadFunc(ctx, filePath, dst)
}

// DownloadCalls gets all the calls that were made to Download.
// Check the length with:
//
//	len(mockedtelegramAPI.DownloadCalls())
func (mock *TelegramAPI) DownloadCalls() []struct {
	Ctx      context.Context
	FilePath string
	Dst      io.Writer
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Dst      io.Writer
	}
	mock.lockDownload.RLock()
	calls = mock.calls.Download
	mock.lockDownload.RUnlock()
	return calls
}

// GetFile calls GetFileFunc.
func (mock *TelegramAPI) GetFile(ctx context.Context, fileID string) (telegram.File, error) {
	if mock.GetFileFunc == nil {
		panic("TelegramAPI.GetFileFunc: method is nil but telegramAPI.GetFile was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		FileID string
	}{
		Ctx:    ctx,
		FileID: fileID,
	}
	mock.lockGetFile.Lock()
	mock.calls.GetFile = append(mock.calls.GetFile, callInfo)
	mock.lockGetFile.Unlock()
	return mock.GetFileFunc(ctx, fileID)
}

// GetFileCalls gets all the calls that were made to GetFile.
// Check the length with:
//
//	len(mockedtelegramAPI.GetFileCalls())
func (mock *TelegramAPI) GetFileCalls() []struct {
	Ctx    context.Context
	FileID string
} {
	var calls []struct {
		Ctx    context.Context
		FileID string
	}
	mock.lockGetFile.RLock()
	calls = mock.calls.GetFile
	mock.lockGetFile.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *TelegramAPI) SendMessage(ctx context.Context, chatID int64, text string, parseMode string, replyTo int64, threadID int64) (telegram.Message, error) {
	if mock.SendMessageFunc == nil {
		panic("TelegramAPI.SendMessageFunc: method is nil but telegramAPI.SendMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		Text      string
		ParseMode string
		ReplyTo   int64
		ThreadID  int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		Text:      text,
		ParseMode: parseMode,
		ReplyTo:   replyTo,
		ThreadID:  threadID,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	return mock.SendMessageFunc(ctx, chatID, text, parseMode, replyTo, threadID)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedtelegramAPI.SendMessageCalls())
func (mock *TelegramAPI) SendMessageCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	Text      string
	ParseMode string
	ReplyTo   int64
	ThreadID  int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		Text      string
		ParseMode string
		ReplyTo   int64
		ThreadID  int64
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}
