// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/alkk/tg-mcp/pkg/telegram"
)

// BotAPI is a mock implementation of ingest.botAPI.
//
//	func TestSomethingThatUsesbotAPI(t *testing.T) {
//
//		// make and configure a mocked ingest.botAPI
//		mockedbotAPI := &BotAPI{
//			DeleteWebhookFunc: func(ctx context.Context) error {
//				panic("mock out the DeleteWebhook method")
//			},
//			GetUpdatesFunc: func(ctx context.Context, offset int64, timeout time.Duration) ([]telegram.Update, error) {
//				panic("mock out the GetUpdates method")
//			},
//		}
//
//		// use mockedbotAPI in code that requires ingest.botAPI
//		// and then make assertions.
//
//	}
type BotAPI struct {
	// DeleteWebhookFunc mocks the DeleteWebhook method.
	DeleteWebhookFunc func(ctx context.Context) error

	// GetUpdatesFunc mocks the GetUpdates method.
	GetUpdatesFunc func(ctx context.Context, offset int64, timeout time.Duration) ([]telegram.Update, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteWebhook holds details about calls to the DeleteWebhook method.
		DeleteWebhook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetUpdates holds details about calls to the GetUpdates method.
		GetUpdates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int64
			// Timeout is the timeout argument value.
			Timeout time.Duration
		}
	}
	lockDeleteWebhook sync.RWMutex
	lockGetUpdates    sync.RWMutex
}

// DeleteWebhook calls DeleteWebhookFunc.
func (mock *BotAPI) DeleteWebhook(ctx context.Context) error {
	if mock.DeleteWebhookFunc == nil {
		panic("BotAPI.DeleteWebhookFunc: method is nil but botAPI.DeleteWebhook was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteWebhook.Lock()
	mock.calls.DeleteWebhook = append(mock.calls.DeleteWebhook, callInfo)
	mock.lockDeleteWebhook.Unlock()
	return mock.DeleteWebhookFunc(ctx)
}

// DeleteWebhookCalls gets all the calls that were made to DeleteWebhook.
// Check the length with:
//
//	len(mockedbotAPI.DeleteWebhookCalls())
func (mock *BotAPI) DeleteWebhookCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteWebhook.RLock()
	calls = mock.calls.DeleteWebhook
	mock.lockDeleteWebhook.RUnlock()
	return calls
}

// GetUpdates calls GetUpdatesFunc.
func (mock *BotAPI) GetUpdates(ctx context.Context, offset int64, timeout time.Duration) ([]telegram.Update, error) {
	if mock.GetUpdatesFunc == nil {
		panic("BotAPI.GetUpdatesFunc: method is nil but botAPI.GetUpdates was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Offset  int64
		Timeout time.Duration
	}{
		Ctx:     ctx,
		Offset:  offset,
		Timeout: timeout,
	}
	mock.lockGetUpdates.Lock()
	mock.calls.GetUpdates = append(mock.calls.GetUpdates, callInfo)
	mock.lockGetUpdates.Unlock()
	return mock.GetUpdatesFunc(ctx, offset, timeout)
}

// GetUpdatesCalls gets all the calls that were made to GetUpdates.
// Check the length with:
//
//	len(mockedbotAPI.GetUpdatesCalls())
func (mock *BotAPI) GetUpdatesCalls() []struct {
	Ctx     context.Context
	Offset  int64
	Timeout time.Duration
} {
	var calls []struct {
		Ctx     context.Context
		Offset  int64
		Timeout time.Duration
	}
	mock.lockGetUpdates.RLock()
	calls = mock.calls.GetUpdates
	mock.lockGetUpdates.RUnlock()
	return calls
}
