// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/alkk/tg-mcp/pkg/store"
)

// MessageStore is a mock implementation of ingest.messageStore.
//
//	func TestSomethingThatUsesmessageStore(t *testing.T) {
//
//		// make and configure a mocked ingest.messageStore
//		mockedmessageStore := &MessageStore{
//			UpsertBatchFunc: func(ctx context.Context, msgs []store.Message) error {
//				panic("mock out the UpsertBatch method")
//			},
//		}
//
//		// use mockedmessageStore in code that requires ingest.messageStore
//		// and then make assertions.
//
//	}
type MessageStore struct {
	// UpsertBatchFunc mocks the UpsertBatch method.
	UpsertBatchFunc func(ctx context.Context, msgs []store.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// UpsertBatch holds details about calls to the UpsertBatch method.
		UpsertBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []store.Message
		}
	}
	lockUpsertBatch sync.RWMutex
}

// UpsertBatch calls UpsertBatchFunc.
func (mock *MessageStore) UpsertBatch(ctx context.Context, msgs []store.Message) error {
	if mock.UpsertBatchFunc == nil {
		panic("MessageStore.UpsertBatchFunc: method is nil but messageStore.UpsertBatch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []store.Message
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockUpsertBatch.Lock()
	mock.calls.UpsertBatch = append(mock.calls.UpsertBatch, callInfo)
	mock.lockUpsertBatch.Unlock()
	return mock.UpsertBatchFunc(ctx, msgs)
}

// UpsertBatchCalls gets all the calls that were made to UpsertBatch.
// Check the length with:
//
//	len(mockedmessageStore.UpsertBatchCalls())
func (mock *MessageStore) UpsertBatchCalls() []struct {
	Ctx  context.Context
	Msgs []store.Message
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []store.Message
	}
	mock.lockUpsertBatch.RLock()
	calls = mock.calls.UpsertBatch
	mock.lockUpsertBatch.RUnlock()
	return calls
}
